name: EdgeCoderIOS
options:
  bundleIdPrefix: io.edgecoder
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    PRODUCT_NAME: EdgeCoder
    SWIFT_VERSION: "5.0"
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
targets:
  EdgeCoderIOS:
    type: application
    platform: iOS
    sources:
      - path: EdgeCoderIOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.edgecoder.ios
        INFOPLIST_FILE: EdgeCoderIOS/Info.plist
        CODE_SIGN_ENTITLEMENTS: EdgeCoderIOS/EdgeCoderIOS.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: R68RHRM2H4
        TARGETED_DEVICE_FAMILY: "1,2"
      configs:
        Debug:
          CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: YES
    info:
      path: EdgeCoderIOS/Info.plist
      properties:
        CFBundleDisplayName: EdgeCoder
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: "1"
        CFBundleIconName: AppIcon
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLName: io.edgecoder.ios.oauth
            CFBundleURLSchemes:
              - edgecoder
        UIBackgroundModes:
          - fetch
          - processing
          - bluetooth-central
          - bluetooth-peripheral
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchStoryboardName: LaunchScreen
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
        ITSAppUsesNonExemptEncryption: false
    dependencies:
      - package: llama
packages:
  llama:
    url: https://github.com/ggml-org/llama.cpp
    branch: master
schemes:
  EdgeCoderIOS:
    build:
      targets:
        EdgeCoderIOS: all
    run:
      config: Debug
    archive:
      config: Release
