#!/usr/bin/env bash
set -euo pipefail

echo "=== Fly.io Consolidation Teardown Checklist ==="
echo ""
echo "Prerequisites (verify these FIRST):"
echo "  1. edgecoder-seed is deployed and healthy"
echo "     Run: fly status -a edgecoder-seed"
echo "  2. Portal updated to reference seed node"
echo "     Run: fly status -a edgecoder-portal"
echo "  3. DNS coordinator.edgecoder.io points to edgecoder-seed"
echo "  4. GitHub Pages deployed for docs.edgecoder.io"
echo ""
echo "Apps to destroy (run manually):"
echo "  fly apps destroy edgecoder-coordinator-2 --yes"
echo "  fly apps destroy edgecoder-inference --yes"
echo "  fly apps destroy edgecoder-control-plane --yes"
echo "  fly apps destroy edgecoder-docs --yes"
echo ""
echo "Post-teardown:"
echo "  - Verify edgecoder-portal still works: curl https://edgecoder.io/health"
echo "  - Verify seed node: curl https://coordinator.edgecoder.io/status"
echo "  - Verify docs: curl https://docs.edgecoder.io"
echo "  - Remove stale Postgres attachments if any"
echo ""
echo "Remaining Fly apps after teardown: edgecoder-portal, edgecoder-seed"
